packages:
  - "examples/*"

catalog:
  "@babel/core": ^7.29.7
  "@types/node": ^26.1.1
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.7
  "@vitejs/plugin-react": ^6.1.1
  react: 19.2.3
  react-dom: 19.2.3
  react-native: 0.86.3
  typescript: 7.0.2
  vite: ^8.3.0
